### ISSUE TITLE
No Display value for GNSS

### ISSUE THREAD

**Issue by dwarning** [Rodemfr/MicronetToNMEA#90]
Hi Ronan,
your commit e3f344e36c61213f9c8bb1b548dff5a60c98c30f stops the display for LAT and LON on my MN 100-2.
It is not the introduction of GLL - it is the change:
```
-    if (c == 13)
+    if ((c == 13) || (c == 10))
```

Going back to the former state everything is OK: Display and correct OpenCPN via NMEA and WiFi Adapter.

**Comment by Rodemfr** [comment]
I finally have a bit of time to work again on the project.

I added this patch to handle NMEA sentences from the *shipdriver_pi* plugin of OCPN which was not formatting the sentences correctly. But my implementation had a bug and *shipdriver_pi* has been fixed since.
So I implemented another way to check the end of a sentence by using the '*' character. It seems more robust that the CR/LF codes which are always bringing variability accross the systems.

You can test this implementation in branch "decode_full_rmc"
